import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from 'react'

import './globals.css'
import {Toaster as HotToaster} from "react-hot-toast";
import {Toaster as ChadCnToaster} from "@/components/ui/toaster"
import MainNavbar from "@/components/main-navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${inter.className} `}>
        <HotToaster/>
        <ChadCnToaster/>
        <MainNavbar/>
        {children}
        </body>
        </html>
    )
}
